# Generated by Django 5.0.2 on 2024-02-22 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(3, message='Пароль слишком короткий'), django.core.validators.RegexValidator(message='Пароль должен содержать одну строчную букву, одну заглавную и одну цифру', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)')]),
        ),
    ]
