# Generated by Django 5.0.2 on 2024-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_fileaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccess',
            name='access_type',
            field=models.CharField(choices=[('author', 'Author'), ('co-author', 'Co-Author')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
