# Generated by Django 5.0.2 on 2024-02-26 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_fileaccess_access_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='access_users',
            field=models.ManyToManyField(related_name='access_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
