# Generated by Django 5.0.2 on 2024-02-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
